.TH HTMLSPLIT 1 2015-06-06 "Marvin Gülker" "User Commands"
.mso www.tmac

.SH NAME
htmlsplit \- Split large HTML files into smaller HTML files

.SH SYNOPSIS

.B htmlsplit
.R [-i \fIFILE\fR]
.R { [-o \fIDIR\fR] | [-s \fISEP\fR] }
.R [-x \fIXPATH\fR]
.R [-v]

.SH DESCRIPTION

.PP
The htmlsplit command splits a large HTML file into several smaller
HTML files by parsing it and applying an XPath query repeatedly onto
the larger HTML document. Each location where the XPath query matches
on the given document is remember as a \fIsplit point\fR, which you
can think of as the place the document is to be cut in two (or more)
parts.

The default behaviour is to cut at all \fB<h1>\fR tags found, but by
supplying the \fB-x\fR option you can replace that with any XPath
query you deem useful for your purposes.

If you use the \fB-o\fR option to specify an output directory, that
directory must exist.

.SH OPTIONS

.TP
.B -i \fIFILE\fR
Read input from the given HTML file. If this option is ommitted, input
is read from standard input instead.

.TP
.B -o \fIDIR\fR
Write output to the given directory. For each section found in the
input, one file with format \fIxxxx.html\fR is created in this
directory, where \fIxxxx\fR is replaced by a consecutive number
corresponding to the section found. The text part before the first
split point will receive the file name \fI0000.html\fR. If this option
is not given, output will be printed to the standard output. See also
option \fB-s\fR.

.TP
.B -s \fISEP\fR
When outputting to the standard output (i.e. \fB-o\fR was not given),
use this as the separator between the documents. It defaults to
\fB<!-- HTMLSPLIT -->\fR if not given. May not be longer than 1023
bytes. A newline is automatically appended to this.

.TP
.B -x \fIXPATH\fR
Use \fIXPATH\fR as the XPath query to determine the split points. If
this option is ommited, it defaults to \fB//h1\fR, that is all
\fB<h1>\fR tags will be used as split points. Note that the XPath
query must either be an absolute one (starting with “/”), or one that
starts with “//” (= search on all levels).

.TP
.B -v
Verbose run. This option will make \fBhtmlsplit\fR output more
information during its operation.

.SH NOTES

.PP
Please report any bugs you find to
.URL "mailto:m-guelker@guelkerdev.de" "Marvin Gülker".
For any bug report, please include the full output of running
\fBhtmlsplit\fR with the \fB-v\fR option, and, if possible and
applicable, a minimal example HTML file.

.PP
The project’s bugtracker and sourcecode can be browsed on the WWW at
.URL "https://github.com/Quintus/htmlsplit" "GitHub".

.SH BUGS

.PP
If the split points found by this program do not have the same parent
node (e.g. all in the \fB<body>\fR tag on the same level or inside
the same \fB<div>\fR), then unpredictable behaviour will result. They
may be at any depth (and their surroundings will be kept), but they
must be on the same depth. Consider this example:

.PP
    <!DOCTYPE html>
    <html>
      <head>
        <title>Bad example</title>
      </head>
      <body>
        <h1>Split point one</h1>
        <p>Text</p>
        <div class="baddiv">
          <h1>Split point two</h1>
          <p>Text</p>
        </div>
      </body>
    </html>

.PP
The above will result in undefined behaviour, because one split point
is found directly below the \fB<body>\fR tag, and another inside a
nested \fB<div>\fR tag. Thus, ensure that all your split points have
the same parent; in the above example, this could be achieved by
either moving the first \fB<h1>\fR and the following \fB<p>\fR into
the \fB<div>\fR, or by deleting the \fB<div>\fR and assigning its
content to the parent \fB<body>\fR tag.

Another way to mitigate this problem is to restrict the XPath query
used to find the split points by means of the \fB-x\fR option. For the
above example it could be set to \fB-x /html/body/div/h1\fR, in which
case the \fB<h1>\fR outside the \fB<div>\fR would not even be
considered as a split point.

.SH EXAMPLE

.PP
Split a large HTML file at its \fB<h1>\fR sections into several
smaller files:

.PP
    $ mkdir /tmp/split
    $ htmlsplit -i large.html -o /tmp/split

.PP
Split it at \fB<h2>\fR instead:

.PP
    $ htmlsplit -i large.html -o /tmp/split -x '//h2'

.PP
Split at all \fB<h2>\fR tags inside the \fB<div>\fR with CSS class
\fBmain\fR inside the \fB<body>\fR tag:

.PP
    $ htmlsplit -i large.html -o /tmp/split \e
      -x '/html/body/div[@class="main"]/h2'

.PP
Split standard input:

.PP
    $ cat large.html | htmlsplit -o /tmp/split

.SH SEE ALSO

.BR split(1)
